export GCP_PROJECT_ID="cedar-defender-475318-r5"
export GCP_REGION="asia-south1"
export VERTEX_AI_LOCATION="asia-south1"
export GCS_BUCKET_NAME="online-marketplace"
export GCS_UPDATES_BASE_PATH="embeddings/updates"
export MONGODB_DATABASE="test"
export MONGODB_COLLECTION="artworks"
export MONGODB_SECRET_NAME="mongodb-connection-string"
export EMBEDDING_MODEL="multimodalembedding@001"
export EMBEDDING_DIMENSION="1408"
export VERTEX_AI_INDEX_ID="projects/529829749133/locations/asia-south1/indexes/2394234947993862144"
export EMBEDDING_BATCH_SIZE="5"
export UPDATE_WINDOW_HOURS="24"
export TEST_MODE="true"
export TEST_LIMIT="10"

echo "✅ Environment variables set for Phase 3 local testing"